name: The Stand-Up Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55378
title: Stuff that matters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f29200'
    - '#266b7b'
    - '#e9ba68'
    - '#9abbc4'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
